// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqJIpg7TMdUDj_1XO-uxSfcnVdR4fTR0',
    appId: '1:937786460707:android:b0719236b8f43b99a87f96',
    messagingSenderId: '937786460707',
    projectId: 'pocket-personal--1543965339641',
    databaseURL: 'https://pocket-personal-1543965339641.firebaseio.com',
    storageBucket: 'pocket-personal--1543965339641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJMke27mCIWpEpSisgS1hs1BsN8yQqE6o',
    appId: '1:937786460707:ios:ecfa6388605a0724a87f96',
    messagingSenderId: '937786460707',
    projectId: 'pocket-personal--1543965339641',
    databaseURL: 'https://pocket-personal-1543965339641.firebaseio.com',
    storageBucket: 'pocket-personal--1543965339641.appspot.com',
    androidClientId: '937786460707-gvrkpohdp2v0gcl1a4qjfnqgpa1t8p93.apps.googleusercontent.com',
    iosClientId: '937786460707-7pdtu1p06cgdfc7br3h3a5m2iab88l58.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketpersonaltrainer',
  );
}
